version: '3.9'

services:
  php:
    working_dir: /var/www
    build:
      context: docker/php-fpm/local
    volumes:
      - ./:/var/www
    user: root
    entrypoint: "php-fpm"
    command:
      - "-R"
  db:
    image: postgres:14.2-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - '54320:5432'

  nginx:
    image: nginx:1.17
    ports:
      - "85:80"
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/local/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_volume: ~
